trainset:
  name: flyingthings3d
  root_dir: G:/CV-dataset/OpticalFlow/Flyingthings3D_subset/processed
  split: train
  n_workers: 4
  full: false
  drop_last: true

  n_points: 8192
  max_depth: 35.0

  augmentation:
    enabled: true
    color_jitter:
      enabled: false
    random_horizontal_flip:
      enabled: true
    random_vertical_flip:
      enabled: true
    random_crop:
      enabled: false
    random_scale:
      enabled: false

valset:
  name: flyingthings3d
  root_dir: G:/CV-dataset/OpticalFlow/Flyingthings3D_subset/processed
  split: val
  n_workers: 4
  full: true

  n_points: 8192
  max_depth: 35.0

  augmentation:
    enabled: false

model:
  batch_size: 8
  freeze_bn: false

  ids:
    enabled: true
    sensor_size_divisor: 32

  pwc2d:
    norm:
      feature_pyramid: batch_norm
      flow_estimator: null
      context_network: null
    max_displacement: 4

  pwc3d:
    norm:
      feature_pyramid: batch_norm
      correlation: null
      flow_estimator: null
    k: 16

  loss2d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l2

  loss3d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l2

training:
  max_epochs: 200
  optimizer: adam
  lr:
    init_value: 0.0008
    momentum: 0.9
    decay_rate: 0.5
    decay_milestones: [60, 120，160]
  weight_decay: 0.000001
  bias_decay: 0.0

log:
  dir: outputs/pretrain
  run_name: pretrain
  save_ckpt: true
  save_ckpt_every_n_epochs: 2
  save_summary_every_n_steps: 100

ckpt:
  path: null
  resume: false

port: random  # for multi-gpu training
amp: false
